name: switch_config
description: "A new Flutter project."
publish_to: none           # Empêche la publication accidentelle sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & icônes
  cupertino_icons: ^1.0.8

  # Réseau & navigation
  dio: ^5.8.0+1
  go_router: ^15.1.2
  flutter_map: ^8.1.1
  image_picker: ^1.1.2

  # State management & stockage
  get: ^4.7.2
  get_storage: ^2.1.1
  equatable: ^2.0.7
  flutter_map_location_marker: ^10.0.2

  # Internationalisation
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1
  flutter_gen_runner: ^5.10.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.2
  flutter_secure_storage: ^9.2.4
  mobile_scanner:
  geolocator: ^13.0.4
  latlong2: ^0.9.1
  intl_phone_field: ^3.2.0
  mime: ^1.0.0
  flutter_launcher_icons: ^0.14.3


  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app_odn_digi.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
